server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bilgeadam_db
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    date-format: yyyy-MM-dd

  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true